version: "3.8"
services:
  database:
    image: timescale/timescaledb:latest-pg14
    container_name: database
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    user: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  server:
    container_name: server
    ports:
      - "8080:8080"
    build:
      context: ${PWD}
      target: test
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: breathe_air
      DATABASE_HOST: database
      REDIS_HOST: redis
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      # These volumes are mounted at run time
      - ${PWD}:/app
      - .bash_history:/root/.bash_history
