# fly.toml app configuration file generated for breathe-air on 2023-09-21T19:31:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "breathe-air"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="machine_data"
  destination="/data"

[processes]
  # The command below is used to launch a Rails server; be sure to
  # replace with the command you're using to launch your server.
  app = "uvicorn main:app --host 0.0.0.0 --port 8080"
  cron = "supercronic /app/crontab"

[[services]]
  processes = ["app"]