"""Add is_data_ok column

Revision ID: 39a00e3eb7f1
Revises: cbf3aa0119c2
Create Date: 2024-03-11 21:21:21.004332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a00e3eb7f1'
down_revision: Union[str, None] = 'cbf3aa0119c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('sensor_data_time_idx', table_name='sensor_data')
    op.add_column('site', sa.Column('is_data_ok', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'is_data_ok')
    op.create_index('sensor_data_time_idx', 'sensor_data', [sa.text('time DESC')], unique=False)
    # ### end Alembic commands ###
