"""request_log

Revision ID: e11be1940ae9
Revises: e6899638a13d
Create Date: 2023-11-08 22:36:00.731599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e11be1940ae9"
down_revision: Union[str, None] = "e6899638a13d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_request_log_time"), "request_log", ["time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_request_log_time"), table_name="request_log")
    op.drop_table("request_log")
    # ### end Alembic commands ###
